### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by NathanTech7713** [JavaChilly/dome-client.js#15]
Hi there,
I think I may have spoke with the dev before about this issue, but unfortunately it no resolution could be reached.
The full error is below, hopefully someone can advise:
/dome-client.js/node_modules/express/node_modules/deb
 ug/src/node.js:120                                                              
 exports.inspectOpts = Object.keys(process.env).filter(key => {                  
                                                            ^                    
 SyntaxError: Unexpected token >                                                 
     at Module._compile (module.js:439:25)                                       
     at Object.Module._extensions..js (module.js:474:10)                         
     at Module.load (module.js:356:32)                                           
     at Function.Module._load (module.js:312:12)                                 
     at Module.require (module.js:364:17)                                        
     at require (module.js:380:17)                                               
     at Object.<anonymous> (/var/www/html/moo/mudclient/dome-client.js/node_modul
 es/express/node_modules/debug/src/index.js:9:19)                                
     at Module._compile (module.js:456:26)                                       
     at Object.Module._extensions..js (module.js:474:10)                         
     at Module.load (module.js:356:32)                                           
 error: Forever detected script exited with code: 8                              

I've done some research on this, and aparrently its to do with some version of node.js supporting es6 modules or something?

**Comment by sevenecks** [comment]
What version of node are you using?

**Comment by NathanTech7713** [comment]
A very old one, apparently. My apologies
